apiVersion: operator.openshift.io/v1alpha1
kind: ZeroTrustWorkloadIdentityManager
metadata:
  name: cluster
  labels:
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: zero-trust-workload-identity-manager
spec:
  trustDomain: apps.agentic-ai-demo.sandbox1133.opentlc.com
  clusterName: agentic-ai-demo-tlrpb
  bundleConfigMap: spire-bundle
