apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: agentic-ai
data:
  MODEL_URL: http://llama-3-2-3b-instruct-predictor.agentic-llm.svc.cluster.local:8080/v1
  MODEL_NAME: llama-3-2-3b-instruct
  MLFLOW_TRACKING_URI: https://mlflow.redhat-ods-applications.svc:8443/mlflow
  MLFLOW_TRACKING_AUTH: kubernetes-namespaced
  MLFLOW_K8S_INTEGRATION: "true"
  MLFLOW_WORKSPACE: agentic-ai
  MLFLOW_TRACKING_INSECURE_TLS: "true"
  INCIDENT_ID: "1042"
  TEMPERATURE: "0.9"
  MAX_STEPS: "12"
  SPIFFE_ENDPOINT_SOCKET: unix:///spiffe-workload-api/spire-agent.sock
